### ISSUE TITLE
Thank you - missing steps in tutorial

### ISSUE THREAD

**Issue by yo8aiv** [drlight17/nc-talk-rec-docker#1]
Thank you - missing steps in tutorial

Hi. thanks a lot for putting this here, i was banging my head since  a long time. 
Could you explain. if you did your yaml in portainer ? .. or wich one , i'm almost there and i feel like im getting crazy.
also how did you genereate your certificates ..?? locally .

thanks in advance.

**Comment by drlight17** [comment]
> if you did your yaml in portainer ?

No, used a reference from [here ](https://help.nextcloud.com/t/how-to-setup-nextcloud-talk-recording-backend/159145/60) and made it "workable" for my needs =) manually

> how did you genereate your certificates ..?? locally .

I don't use self-signed certificates. I use letsencrypt certificates with nginx proxy (see config example in [README](https://github.com/drlight17/nc-talk-rec-docker/blob/main/README.md))

**Comment by yo8aiv** [comment]
thanks for your fast answers  and for the link. trying this in portainer.
Cheers.
